OPENROUTER_API_KEY = "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"

username_input = "kirito"
password_input = "otirik"

SENDGRID_API_KEY = "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"
EMAIL_SENDER = "maiyaadhikari2017@gmail.com"
EMAIL_RECEIVER = "kiritootirik578@gmail.com"
