apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'streamlit-app'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['streamlit-service:8000']  # ✅ This must be 8000
