name: Basic CI for Streamlit App with Prometheus

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      prometheus:
        image: prom/prometheus:latest
        ports:
          - 9090:9090
        # Removed health check options to prevent container start failures

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements/requirements.txt


      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics || true

      - name: Run basic Streamlit check
        run: |
          echo "Checking Streamlit app can start"
          streamlit run app/main.py --server.headless true --server.port 8501 &
          sleep 10
          curl -f http://localhost:8501 || (echo "Streamlit not running" && exit 1)
          pkill streamlit || true

      - name: Check metrics endpoint
        run: |
          curl -f http://localhost:8000/metrics || (echo "Metrics endpoint not reachable" && exit 1)

      - name: Check Prometheus UI endpoint
        run: |
          curl -f http://localhost:9090/metrics || (echo "Prometheus metrics not reachable" && exit 1)
