name: CI for Streamlit App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements/requirements.txt

      - name: Lint code
        run: |
          pip install flake8
          flake8 PRODUCT_APP/ --count --select=E9,F63,F7,F82 --show-source --statistics || true

      - name: Run Streamlit app check
        run: |
          streamlit run PRODUCT_APP/main.py --server.headless true --server.port 8501 &
          sleep 10
          curl -f http://localhost:8501 || (echo "Streamlit app is not running" && exit 1)
          pkill streamlit || true
