name: Basic CI for Streamlit App with Prometheus

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      prometheus:
        image: prom/prometheus:latest
        ports:
          - 9090:9090
        # Removed health checks for simplicity

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements/requirements.txt

      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 PRODUCT_APP/ --count --select=E9,F63,F7,F82 --show-source --statistics || true

      - name: Run basic Streamlit + metrics check
        run: |  
          echo "Starting Streamlit app with metrics"
          streamlit run PRODUCT_APP/main.py --server.headless true --server.port 8501 &
          sleep 15  # Give enough time for both UI (8501) and metrics (8000) to boot

          echo "Checking UI"
          curl -f http://localhost:8501 || (echo "Streamlit UI not reachable" && exit 1)

          echo "Checking metrics"
          curl -f http://localhost:8000/metrics || (echo "Metrics endpoint not reachable" && exit 1)

          pkill streamlit || true

      - name: Check Prometheus UI endpoint
        run: |
          curl -f http://localhost:9090/metrics || (echo "Prometheus metrics not reachable" && exit 1)
