# .github/workflows/ci-basic.yaml
name: Basic CI for Streamlit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics || true

    - name: Run basic Streamlit check
      run: |
        echo "Checking Streamlit app can start"
        streamlit run app/main.py --server.headless true &
        sleep 5
        pkill streamlit || true
